version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/mysql:5.5
    networks:
    - parrot
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
    parrot:
      external:
        name: default
    parrot:
        driver: bridge
